const employees = [
  {
    id: 1,
    firstName: "Amit",
    lastName: "Sharma",
    gender: "Male",
    email: "amit.sharma@example.com",
    password: "123",
    tasks: [
      {
        title: "Prepare Sales Report",
        description: "Compile the monthly sales data and generate a report.",
        date: "2025-02-05",
        category: "Sales",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Client Meeting",
        description: "Attend the scheduled meeting with XYZ Corp.",
        date: "2025-02-06",
        category: "Meetings",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update CRM Data",
        description: "Ensure all client interactions are recorded in CRM.",
        date: "2025-02-07",
        category: "CRM",
        accepted: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      accepted: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Priya",
    lastName: "Verma",
    gender: "Female",
    email: "priya.verma@example.com",
    password: "123",
    tasks: [
      {
        title: "Design UI Mockups",
        description: "Create wireframes for the new project.",
        date: "2025-02-05",
        category: "Design",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Review Team Feedback",
        description: "Analyze feedback from last sprint review.",
        date: "2025-02-06",
        category: "Management",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prepare Pitch Deck",
        description: "Work on slides for upcoming client presentation.",
        date: "2025-02-07",
        category: "Presentation",
        accepted: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Conduct User Testing",
        description: "Test the latest prototype with users.",
        date: "2025-02-08",
        category: "Testing",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskNumbers: {
      accepted: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    firstName: "Rahul",
    lastName: "Nair",
    gender: "Male",
    email: "rahul.nair@example.com",
    password: "123",
    tasks: [
      {
        title: "Fix API Issues",
        description: "Debug and fix API response errors.",
        date: "2025-02-05",
        category: "Development",
        accepted: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Code Review",
        description: "Review PRs from junior developers.",
        date: "2025-02-06",
        category: "Development",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      accepted: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    firstName: "Sneha",
    lastName: "Iyer",
    gender: "Female",
    email: "sneha.iyer@example.com",
    password: "123",
    tasks: [
      {
        title: "Marketing Strategy",
        description: "Plan and execute a new marketing campaign.",
        date: "2025-02-05",
        category: "Marketing",
        accepted: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "SEO Analysis",
        description: "Optimize website for better search rankings.",
        date: "2025-02-06",
        category: "SEO",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Social Media Content",
        description: "Prepare posts for social media platforms.",
        date: "2025-02-07",
        category: "Social Media",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Email Marketing",
        description: "Schedule and send promotional emails.",
        date: "2025-02-08",
        category: "Marketing",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Customer Engagement",
        description: "Respond to customer queries and feedback.",
        date: "2025-02-09",
        category: "Support",
        accepted: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      accepted: 3,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 5,
    firstName: "Arjun",
    lastName: "Patel",
    gender: "Male",
    email: "arjun.patel@example.com",
    password: "123",
    tasks: [
      {
        title: "Inventory Check",
        description: "Perform routine inventory assessment.",
        date: "2025-02-05",
        category: "Logistics",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Supplier Negotiation",
        description: "Negotiate better pricing with suppliers.",
        date: "2025-02-06",
        category: "Procurement",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Warehouse Audit",
        description: "Ensure compliance with safety regulations.",
        date: "2025-02-07",
        category: "Logistics",
        accepted: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fleet Management",
        description: "Oversee transport and delivery schedules.",
        date: "2025-02-08",
        category: "Operations",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskNumbers: {
      accepted: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
];

const admins = [
  {
    id: 1,
    firstName: "Vikram",
    lastName: "Singh",
    gender: "Male",
    email: "vikram.singh@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admins", JSON.stringify(admins));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admins"));

  return { employees, admin };
};
